import { Student, Meeting, Alert, TimelineEntry, Forecast, Program, PerformanceScore } from './types';

const STUDENTS: Student[] = [
  {
    id: 's1',
    full_name: 'Priya Kumari',
    date_of_birth: '2008-05-15',
    gender: 'Female',
    aadhaar_last4: '1234',
    photo_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya',
    phone: '+91 98765 43210',
    email: 'priya.k@example.com',
    parent_phone: '+91 98765 43200',
    home_village: 'Kudalur',
    district: 'Tiruchirappalli',
    state: 'Tamil Nadu',
    father_name: 'Kumar',
    mother_name: 'Lakshmi',
    family_income_bracket: '₹1-2.5L',
    first_gen_learner: true,
    current_class: '12th',
    institution_name: 'Government Girls Higher Secondary School',
    institution_type: 'Government',
    stream: 'Science',
    aspiration: 'Medical Professional',
    referral_source: 'School Coordinator',
    first_contact_date: '2023-06-01',
    created_at: '2023-06-01T10:30:00Z',
    programs: [
      {
        id: 'pe1',
        student_id: 's1',
        program_id: 'p1',
        program_name: 'Vidhai',
        start_date: '2023-06-01',
        status: 'active',
      },
      {
        id: 'pe2',
        student_id: 's1',
        program_id: 'p2',
        program_name: 'Mentorship',
        start_date: '2023-08-01',
        status: 'active',
      },
    ],
    performance_score: 82,
    status: 'active',
    last_activity: '2024-03-20T14:30:00Z',
    forecast: {
      educational_path: 'Medicine (NEET) → Government Medical College',
      degree_probability: 0.88,
      career_outcome: 'Physician / Surgeon',
      risk_factors: [],
      generated_at: '2024-03-20T10:00:00Z',
    },
  },
  {
    id: 's2',
    full_name: 'Arjun Raj',
    date_of_birth: '2007-12-10',
    gender: 'Male',
    aadhaar_last4: '5678',
    phone: '+91 97654 32100',
    email: 'arjun.r@example.com',
    parent_phone: '+91 97654 32090',
    home_village: 'Villupuram',
    district: 'Villupuram',
    state: 'Tamil Nadu',
    father_name: 'Rajesh',
    mother_name: 'Asha',
    family_income_bracket: '₹0.5-1L',
    first_gen_learner: true,
    current_class: '11th',
    institution_name: 'Zion Matriculation School',
    institution_type: 'Private',
    stream: 'Science',
    aspiration: 'Engineer',
    referral_source: 'NGO Partner',
    first_contact_date: '2023-08-15',
    created_at: '2023-08-15T09:00:00Z',
    programs: [
      {
        id: 'pe3',
        student_id: 's2',
        program_id: 'p1',
        program_name: 'Vidhai',
        start_date: '2023-08-15',
        status: 'active',
      },
      {
        id: 'pe4',
        student_id: 's2',
        program_id: 'p3',
        program_name: 'Hostels',
        start_date: '2023-08-15',
        status: 'active',
      },
      {
        id: 'pe5',
        student_id: 's2',
        program_id: 'p2',
        program_name: 'Mentorship',
        start_date: '2024-01-01',
        status: 'active',
      },
    ],
    performance_score: 61,
    status: 'watch',
    last_activity: '2024-03-15T10:15:00Z',
    forecast: {
      educational_path: 'Engineering (JEE Main) → State Engineering College',
      degree_probability: 0.65,
      career_outcome: 'Software Developer',
      risk_factors: ['Recent attendance drop', 'Math performance below target'],
      generated_at: '2024-03-20T10:00:00Z',
    },
  },
  {
    id: 's3',
    full_name: 'Deepa Mohan',
    date_of_birth: '2009-03-22',
    gender: 'Female',
    aadhaar_last4: '9012',
    phone: '+91 96543 21098',
    email: 'deepa.m@example.com',
    parent_phone: '+91 96543 21088',
    home_village: 'Karur',
    district: 'Karur',
    state: 'Tamil Nadu',
    father_name: 'Mohan',
    mother_name: 'Divya',
    family_income_bracket: '₹1-2.5L',
    first_gen_learner: false,
    current_class: '10th',
    institution_name: 'Karur Public School',
    institution_type: 'Private',
    stream: undefined,
    aspiration: 'Civil Service',
    referral_source: 'School Recommendation',
    first_contact_date: '2024-01-10',
    created_at: '2024-01-10T11:20:00Z',
    programs: [
      {
        id: 'pe6',
        student_id: 's3',
        program_id: 'p1',
        program_name: 'Vidhai',
        start_date: '2024-01-10',
        status: 'active',
      },
      {
        id: 'pe7',
        student_id: 's3',
        program_id: 'p4',
        program_name: 'NP Fellowship',
        start_date: '2024-01-15',
        status: 'active',
      },
    ],
    performance_score: 78,
    status: 'active',
    last_activity: '2024-03-22T15:45:00Z',
  },
  {
    id: 's4',
    full_name: 'Varun Krishnan',
    date_of_birth: '2006-07-05',
    gender: 'Male',
    aadhaar_last4: '3456',
    phone: '+91 95432 10987',
    email: 'varun.k@example.com',
    parent_phone: '+91 95432 10977',
    home_village: 'Madurai',
    district: 'Madurai',
    state: 'Tamil Nadu',
    family_income_bracket: '₹2.5-5L',
    first_gen_learner: false,
    current_class: '12th',
    institution_name: 'Sairam International School',
    institution_type: 'Private',
    stream: 'Commerce',
    aspiration: 'Chartered Accountant',
    referral_source: 'Alumni',
    first_contact_date: '2023-04-05',
    created_at: '2023-04-05T08:30:00Z',
    programs: [
      {
        id: 'pe8',
        student_id: 's4',
        program_id: 'p2',
        program_name: 'Mentorship',
        start_date: '2023-04-05',
        status: 'active',
      },
    ],
    performance_score: 45,
    status: 'at_risk',
    last_activity: '2024-03-10T09:00:00Z',
  },
];

const MEETINGS: Meeting[] = [
  {
    id: 'm1',
    student_id: 's1',
    student_name: 'Priya Kumari',
    mentor_id: 'mentor1',
    mentor_name: 'Dr. Rajesh Kumar',
    scheduled_at: '2024-03-28T15:00:00Z',
    status: 'scheduled',
    created_at: '2024-03-20T10:00:00Z',
  },
  {
    id: 'm2',
    student_id: 's2',
    student_name: 'Arjun Raj',
    mentor_id: 'mentor2',
    mentor_name: 'Ms. Anita Sharma',
    scheduled_at: '2024-03-25T14:00:00Z',
    status: 'completed',
    transcript: 'Discussed weak performance in mathematics. Identified need for additional tutoring. Arjun to attend 3 sessions per week starting next week. Follow-up scheduled in 2 weeks.',
    ai_summary: 'Performance review meeting. Action: Increase tutoring frequency to 3x/week for mathematics.',
    action_items: [
      {
        task: 'Arrange additional math tutoring',
        owner: 'Mentor',
        deadline: '2024-03-27',
      },
      {
        task: 'Solve practice problems (2 hours daily)',
        owner: 'Arjun Raj',
        deadline: '2024-04-01',
      },
    ],
    recording_url: 'https://example.com/meeting-m2-recording',
    created_at: '2024-03-23T16:00:00Z',
  },
  {
    id: 'm3',
    student_id: 's1',
    student_name: 'Priya Kumari',
    mentor_id: 'mentor1',
    mentor_name: 'Dr. Rajesh Kumar',
    scheduled_at: '2024-03-15T10:30:00Z',
    status: 'completed',
    transcript: 'Discussed NEET preparation strategy. Priya is performing well in Biology. Reviewing Physics topics for February test. Encouraged to maintain current pace.',
    ai_summary: 'NEET preparation on track. Strengths in Biology. Continue current study schedule.',
    action_items: [
      {
        task: 'Complete Physics chapter review',
        owner: 'Priya Kumari',
        deadline: '2024-03-20',
      },
    ],
    recording_url: 'https://example.com/meeting-m3-recording',
    student_mood: 'Confident',
    created_at: '2024-03-15T10:30:00Z',
  },
];

const ALERTS: Alert[] = [
  {
    id: 'a1',
    student_id: 's2',
    student_name: 'Arjun Raj',
    mentor_id: 'mentor2',
    mentor_name: 'Ms. Anita Sharma',
    alert_type: 'score_drop',
    severity: 'critical',
    description: 'Performance score dropped from 72 to 61 in the last 2 weeks. Significant decline in math and physics.',
    suggested_action: 'Schedule immediate mentoring session to assess challenges and create intervention plan',
    created_at: '2024-03-19T08:00:00Z',
  },
  {
    id: 'a2',
    student_id: 's4',
    student_name: 'Varun Krishnan',
    alert_type: 'missed_sessions',
    severity: 'critical',
    description: 'Missed 3 consecutive mentorship sessions without notification. Last activity was 2 weeks ago.',
    suggested_action: 'Contact student and mentor to understand barriers. Consider re-engagement plan.',
    created_at: '2024-03-20T09:30:00Z',
  },
  {
    id: 'a3',
    student_id: 's3',
    student_name: 'Deepa Mohan',
    alert_type: 'no_checkin',
    severity: 'warning',
    description: 'Hostel check-in not completed for the current month. Please update status.',
    suggested_action: 'Contact hostel warden to confirm Deepa is in hostel and submit check-in.',
    created_at: '2024-03-21T14:00:00Z',
  },
];

const TIMELINE: TimelineEntry[] = [
  {
    id: 'te1',
    type: 'enrollment',
    date: '2023-06-01',
    title: 'Enrolled in Vidhai',
    description: 'Priya was enrolled in the scholarship program',
    program: 'Vidhai',
  },
  {
    id: 'te2',
    type: 'enrollment',
    date: '2023-08-01',
    title: 'Enrolled in Mentorship',
    description: 'Assigned mentor: Dr. Rajesh Kumar',
    program: 'Mentorship',
  },
  {
    id: 'te3',
    type: 'interaction',
    date: '2023-09-15',
    title: 'Mentor Session: Study Planning',
    description: 'Discussed NEET preparation strategy and created 12-month study plan',
    program: 'Mentorship',
    expandable: true,
  },
  {
    id: 'te4',
    type: 'score_change',
    date: '2023-10-20',
    title: 'Performance Score Updated',
    description: 'Score increased from 68 to 75',
    metadata: { oldScore: 68, newScore: 75, delta: 7 },
  },
  {
    id: 'te5',
    type: 'meeting',
    date: '2024-03-15',
    title: 'Video Meeting: NEET Progress Review',
    description: 'Meeting with Dr. Rajesh Kumar',
    program: 'Mentorship',
    expandable: true,
    metadata: {
      meetingId: 'm3',
      summary: 'NEET preparation on track. Strengths in Biology.',
      actions: ['Complete Physics chapter review'],
    },
  },
];

const PROGRAMS: Program[] = [
  {
    id: 'p1',
    name: 'Vidhai',
    description: 'Scholarship program for deserving students',
    is_active: true,
  },
  {
    id: 'p2',
    name: 'Mentorship',
    description: 'One-on-one mentoring for career guidance',
    is_active: true,
  },
  {
    id: 'p3',
    name: 'Hostels',
    description: 'Hostel support for rural students',
    is_active: true,
  },
  {
    id: 'p4',
    name: 'NP Fellowship',
    description: 'Nammadhu Palli Fellowship for high-impact students',
    is_active: true,
  },
];

const PERFORMANCE_SCORES: PerformanceScore[] = [
  {
    id: 'ps1',
    student_id: 's1',
    score: 82,
    breakdown: {
      attendance: 95,
      academics: 88,
      milestones: 80,
      recency: 85,
    },
    computed_at: '2024-03-20T10:00:00Z',
  },
  {
    id: 'ps2',
    student_id: 's2',
    score: 61,
    breakdown: {
      attendance: 75,
      academics: 58,
      milestones: 65,
      recency: 52,
    },
    computed_at: '2024-03-20T10:00:00Z',
  },
];

export const mockData = {
  students: STUDENTS,
  meetings: MEETINGS,
  alerts: ALERTS,
  timeline: TIMELINE,
  programs: PROGRAMS,
  performanceScores: PERFORMANCE_SCORES,
};

export default mockData;
